import { MetadataRoute } from "next";
import { getBaseUrl } from "@/lib/seo";

const baseUrl = getBaseUrl();

/** Public routes to include in sitemap. Excludes dashboard, auth, blocked, and dynamic [id] pages. */
const staticPaths: string[] = [
  "/",
  "/about",
  "/contact",
  "/support",
  "/terms-and-conditions",
  "/privacy-policy",
  "/company-information",
  "/company-information/private-limited",
  "/company-information/public-limited",
  "/company-information/one-person-company",
  "/company-information/section-8",
  "/company-information/nidhi-company",
  "/company-information/producer-company",
  "/registration",
  "/registration/gst-registration",
  "/registration/llp-registration",
  "/registration/partnership-firm",
  "/registration/sole-proprietorship",
  "/registration/msme-udyam-registration",
  "/registration/startup-india-registration",
  "/registration/ngo-registration",
  "/registration/epfo",
  "/registration/iec-registration",
  "/registration/digital-signature",
  "/registration/pan-apply",
  "/registration/tan-apply",
  "/registration/pt-tax",
  "/registration/esic",
  "/registration/industry-license",
  "/registration/gumusta-shop-registration",
  "/registration/fassai-food-license",
  "/taxation",
  "/taxation/income-tax",
  "/taxation/gst-filing",
  "/taxation/tds-returns",
  "/taxation/tax-planning",
  "/taxation/pt-tax-filing",
  "/taxation/corporate-tax-filing",
  "/taxation/payroll-tax",
  "/taxation/epfo-filing",
  "/taxation/esic-filing",
  "/trademark-iso",
  "/trademark-iso/trademark",
  "/trademark-iso/iso-9001",
  "/trademark-iso/iso-14001-certification",
  "/trademark-iso/copyright-registration",
  "/roc-returns",
  "/roc-returns/annual-filing",
  "/roc-returns/board-resolutions",
  "/roc-returns/director-changes",
  "/roc-returns/share-transfer",
  "/advisory",
  "/advisory/business-strategy-consulting",
  "/advisory/legal-compliance-advisory",
  "/advisory/financial-planning-analysis",
  "/advisory/digital-transformation",
  "/advisory/assistance-for-fund-raising",
  "/advisory/startup-mentoring",
  "/advisory/tax-plan-analysis",
  "/advisory/other-finance-related-services",
  "/advisory/hr-organizational-development",
  "/reports",
  "/reports/project-reports",
  "/reports/cma-reports",
  "/reports/dscr-reports",
  "/reports/bank-reconciliation",
  "/tools",
  "/tools/income-tax-calculator",
  "/tools/gst-calculator",
  "/tools/emi-calculator",
  "/tools/salary-calculator",
  "/tools/sip-calculator",
  "/tools/ppf-calculator",
  "/tools/rd-calculator",
  "/tools/nps-calculator",
  "/tools/epf-calculator",
  "/tools/hra-calculator",
  "/tools/home-loan-emi",
  "/tools/mutual-fund-calculator",
  "/tools/compound-interest",
  "/tools/currency-converter",
  "/tools/gst-number-search",
  "/tools/ifsc-code-search",
  "/tools/hsn-code-finder",
  "/tools/gst-search-by-name",
  "/tools/tax-saving",
  "/tools/it-refund-status",
  "/tools/rent-receipts",
  "/tools/gold-rates",
];

export default function sitemap(): MetadataRoute.Sitemap {
  const lastModified = new Date();

  return staticPaths.map((path) => ({
    url: `${baseUrl}${path}`,
    lastModified,
    changeFrequency: path === "/" ? "weekly" : ("monthly" as const),
    priority: path === "/" ? 1 : 0.8,
  }));
}
